### ISSUE TITLE
mydmx problem

### ISSUE THREAD

**Issue by lisjakjanko** [jesselang/mydmx#1]
Hi
First of all, thanks a lot for your work on mydmx drivers.

I have a mydmx device, and I would like to use it with linux. 
I downloaded your package and tried to install the drivers, but it give me an error while using sudo make command.

This is the result:
make -C /lib/modules/3.13.0-36-generic/build M=/home/jankolisjak/Documents/mydmx/src modules
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-36-generic'
  CC [M]  /home/jankolisjak/Documents/mydmx/src/mydmx.o
/home/jankolisjak/Documents/mydmx/src/mydmx.c: In function ‘mydmx_open’:
/home/jankolisjak/Documents/mydmx/src/mydmx.c:84:3: error: implicit declaration of function ‘err’ [-Werror=implicit-function-declaration]
   err("%s - error, can't find device for minor %d",
   ^
cc1: some warnings being treated as errors
make[2]: *** [/home/jankolisjak/Documents/mydmx/src/mydmx.o] Error 1
make[1]: *** [_module_/home/jankolisjak/Documents/mydmx/src] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.13.0-36-generic'
make: **\* [default] Error 2

Thanks a lot

**Comment by jesselang** [comment]
Thanks for your interest in the mydmx driver.

I get the same results you do when trying to build against a 3.14 kernel.

I believe I used the USB skeleton driver from the 3.2 version of the kernel. It appears there have been some changes to that driver starting in 3.5.

Thanks for making me aware of the issue. I will review the changes and work on getting these errors resolved.

Thanks!

**Comment by lisjakjanko** [comment]
Thank you very much for your fast response.

Please inform me when you will have some results :)

If I can do anything to help ypu, let me know.

Best regards!

Janko

2014-10-12 21:34 GMT+02:00 Jesse Lang notifications@github.com:

**Comment by jesselang** [comment]
I've made changes which allow the module to build against linux-3.16. I think you'll find it will build against linux-3.13 as well.

I couldn't find the mydmx device to test. I'll test once I come across the device.

In the meantime, please pull the branch named "issue-1", and let me know your results. If the module builds and the test program works for you, I'll merge the change into master.

Thanks!

**Comment by jesselang** [comment]
I merged the branch. Closing.
